version: "{build}"

environment:
  nodejs_version: "4"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm -g install npm@3
  - set PATH=%APPDATA%\npm;%PATH%
  - npm --version
  - npm cache clean
  - npm install

test_script:
  - npm run test:project-stub

build: off
